import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import DateComponent from "../components/DateComponent";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Closed day Fetching to api-france</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Closed day Fetching to api-france</h1>
        <DateComponent />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps(context) {
  const url =
    "https://etalab.github.io/jours-feries-france-data/json/metropole.json";
  const res = await fetch(url);
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { data }, // will be passed to the page component as props
  };
}
